### ISSUE TITLE
weather data directory doesn't get transferred to site-packages if python setup.py is used to install

### ISSUE THREAD

**Issue by cdfassnacht** [Keck-DataReductionPipelines/KAI#17]
Hi, I used the setup.py to install KAI on my system, via `python setup.py install` in the top-level directory.  Things mostly work, but when calling makelog_and_prep_images an exception gets raised because it can't find the weather file that it is looking for.  I was able to address this problem by copying over the kai/reduce/weather directory from where I had done my `git clone` to my anaconda lib/python2.7/site-packages/kai[lots of numbers and letters]/kai/reduce directory.

I think that there is some way to copy data directories into the system installation of a package, although I always have to look it up for my own code.

**Comment by cdfassnacht** [comment]
I have the same problem with the masks directory as well.  In fact, none of the subdirectories that are in the kai/reduce directory get transferred

**Comment by jluastro** [comment]
Fixed in v1.0.1.
