### ISSUE TITLE
fail at go()

### ISSUE THREAD

**Issue by TmGao** [Keck-DataReductionPipelines/KAI#3]
Hi!

Thank you for developing this package! I'm trying to use this pipeline to process some NIRC2 images of galaxies. At first I installed a Pyraf environment alongside Python 2.7, as recommended by AstroConda, but failed to install KAI. So I tried Python 3.7 instead, and succeeded to install KAI.

To process the data, I followed the steps in TheReductionGuide.ipynb. Everything went right until the final step (go()). It told me that I needed to install 'pydrizzle'. Since it was unable to install 'pydrizzle' via Conda at that time (it requires python 2.7,3.4 or 3.5), I directly put 'pydrizzle' in 'site-packages'. Then it told me that it couldn't import 'numerixenv', which was also an outdated module. To solve that, I downgraded my stsci.tools, so that it would contain 'numerixenv'. But again, another TypeError occurred, and this time, I completely didn't know how to solve it.

I also tried the old version of KAI (https://github.com/jluastro/nirc2). It could be installed under Python 2.7, and this time I could install 'pydrizzle' via Conda. But finally I still failed at go() because of the same problem as above.

Thus, I was wondering if you could give me some instructions about how to install KAI correctly. I mean which version of Python should be used, what dependencies need to be installed, etc. By the way, I'm using macOS 10.14.

Thanks in advance for your help!

**Comment by skterry** [comment]
Hi TmGao,

Sorry for the very late reply! The iraf27 pydrizzle is a known issue, during the installation process I recommend that you simply comment out the following two lines from /your/path/to/anaconda3/envs/iraf27/lib/python2.7/site-packages/pydrizzle/__init__.py:

```
# from stsci.tools import numerixenv
# numerixenv.check()
```

Also, I would recommend checking out and working on the dev branch as that branch is updated more frequently than the main branch right now:
`$git checkout dev`

Hope this is helpful,
Sean

**Comment by abhimat** [comment]
I was just investigating this as well. It seems that the newer versions of stsci-tools are no longer compatible with pydrizzle because of this import issue… This `numerixenv` problem is no longer an issue if you require an earlier version of `stsci.tools=3.4.1` in your conda environment. Perhaps we should provide a conda environment yml file with the specific package versions that work since the default astroconda iraf27 installation no longer works?

**Comment by abhimat** [comment]
The conda environment file copied below works for me. If this works for others, perhaps we can include this as a part of installation instructions.
```yml
name: iraf27
channels:
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - iraf-all
  - pyraf-all
  - stsci
  - python=2.7
  - pydrizzle
  - stsci.tools=3.4.1
  - pip:
    - stsci-tools=3.4
prefix: /Users/abhimat/miniconda3/envs/iraf27

```

**Comment by abhimat** [comment]
Closing this issue, since the latest installation instructions (under [047123c](https://github.com/Keck-DataReductionPipelines/KAI/commit/047123c83172007545f12df13cf392e523c0e5af)) with the provided conda environment file should address this problem.
