### ISSUE TITLE
Bug with directories when running reduce.go()

### ISSUE THREAD

**Issue by dchu808** [Keck-DataReductionPipelines/KAI#5]
I found a bug when running `reduce.go()` regarding the directory structure of the data. When running in the reduce/ directory, it looks for data in the following raw/ directory, which it thinks is in the reduce/ directory: `20aug23os/reduce/raw/`

When I change to the above directory 20aug23os/, `reduce.go()` is able to run through the IMCOMBINE step and make a sky file. However, it then looks for the file in the following location: `20aug23os/kp/calib/masks/supermask.fits`, which should be in the reduce/ directory (and more specifically, the reduce/kp/calib/masks/ directory.

Thanks for the help!

**Comment by abhimat** [comment]
Hi Devin, can you share a copy of your reduce template script? It would be helpful to debug this to see exactly how the keywords are called in your example to cause this bug

**Comment by abhimat** [comment]
Also, just to clarify, all reduction scripts are designed to be run in the reduce/ directory

**Comment by dchu808** [comment]
Thank you! After removing these directory related lines, `go()` was able to run without the directory issues. I think that solved it. I can remove these lines from the code in the repository.
